model:
  input_dim: 1
  hidden_dim: 128
  gru_layers: 2
  dropout: 0.1
  attention: true
  action_dim: 2

ppo:
  gamma: 0.99

training:
  device: "cuda"
  buffer_maxlen: 10000
  save_dir: "checkpoints"
  save_interval_steps: 20000

  # ---- Simulation (훈련) ----
  sim:
    lr: 3.0e-4
    clip_epsilon: 0.2
    entropy_coef: 0.05
    value_coef: 0.5
    update_epochs: 3
    update_interval: 1024
    update_freq: 5

  # ---- Live (실전) ----
  live:
    lr: 1.0e-4
    clip_epsilon: 0.1
    entropy_coef: 0.05
    value_coef: 0.4
    update_epochs: 1
    update_interval: 16
    update_freq: 3

live:
  refresh_interval: 0.5         # loop delay
  save_interval_updates: 5    # 몇 번의 PPO update마다 저장
  save_prefix: "live_model"   # ✅ 선택적 prefix

policy:
  signal_sell_threshold: 0.10  # usdt 비중 10% 이상이면 SELL 신호로 해석
  reward_scale: 3.5
  hold_penalty_lambda: 0.001    # 포지션 유지 패널티
  fee_rate: 0.0001

data:
  window_15m: 15   # 15분봉 시계열 길이
  window_1d: 10    # 일봉 시계열 길이

sim:
  max_steps: 1000
  fee: 0.0001
  init_krw: 10000000